add new file assistants.py to load current assistants list
ryo-ma/gpt-assistants-api-ui pull request #25
Opened 2024-06-30 08:33 UTC by bzbwqz

added new file assistants.py
modified app.py to load current assistants list
ignore the readme change

2024-06-30 22:01 UTC, vietnguyengit requested changes

2024-06-30 22:01 UTC, vietnguyengit commented on README.md
> +
maybe use English?

2024-06-30 22:02 UTC, vietnguyengit requested changes

2024-06-30 22:02 UTC, vietnguyengit commented on assistants.py
> +    return json.dumps(assistants_list)
ending line, and what's the actual benefits?

2024-06-30 22:11 UTC, vietnguyengit requested changes

2024-06-30 22:11 UTC, vietnguyengit commented on app.py
> +    multi_agents = current_assistants()
what are the actual benefits?

2024-06-30 22:11 UTC, vietnguyengit commented on app.py
> +    multi_agents = current_assistants()
why there is a whole new file with extra 35 lines but the current `app.py` has just 1 line removed? are there uncleaned statements?

2024-06-30 22:11 UTC, vietnguyengit commented on assistants.py
> +    return json.dumps(assistants_list)
ending line?

2024-06-30 22:11 UTC, vietnguyengit commented on README.md
> +
is this your personal notes? Use English.

2024-06-30 22:16 UTC, vietnguyengit commented
just my quick look into this PR @ryo-ma , leave the careful checks for you.

2024-07-03 22:48 UTC, bzbwqz commented
I meant to load existing assistants automatically, not to use it from .env. 
sorry for the interrupt and i will close it.

2024-07-03 22:48 UTC, closed without merging